HTTP/1.1 500 Traceback (most recent call last):
  File "/home/shechong/coreProgram/webserv/cgi-bin/upload.py", line 220, in <module>
    with open(file_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shechong/coreProgram/webserv/public/volatile/upload.bla/test.bla'

Content-Type: text/html
Content-Length: 1012

<html>
    <head>
        <style>

body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    margin: 0;
    padding: 20px;
}
h1 {
    color: #4CAF50;
}
table {
    width: 100%;
    border-collapse: collapse;
    border-radius: 10px;
    overflow: hidden;
    padding: 10px;
}
th, td {
    text-align: left;
    background: #fff;
    padding: 10px 5px;
}
a {
    color: #1E90FF;
}
.folder {
    color:rgb(0, 255, 251);
}
.error {
    color: red;
    font-weight: bold;
}
.success {
    color: green;
    font-weight: bold;
}

            h2 {
                color: red;
            }
        </style>
    </head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>Traceback (most recent call last):
  File "/home/shechong/coreProgram/webserv/cgi-bin/upload.py", line 220, in <module>
    with open(file_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shechong/coreProgram/webserv/public/volatile/upload.bla/test.bla'
</p>
    </body>
    </html>